name: Node.js CI
on:  
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: window-latest
    strategy:
      matrix:
        node-version: [22.17.0]
    steps: 
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run test
    - run: npm run build --if-present

