name: Node.js CI - 登录注册功能测试

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test-login-register:
    name: 登录注册功能测试
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 使用 Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: 安装依赖
        run: npm ci

      - name: 代码风格检查
        run: npm run lint

      - name: 运行登录注册功能测试
        run: npm run test -- --testPathPattern="user|login|register" --verbose

      - name: 生成测试覆盖率报告
        run: npm run cov -- --testPathPattern="user|login|register"

      - name: 构建项目
        run: npm run build

      - name: 上传测试覆盖率报告
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov.info
          flags: login-register-tests
          name: login-register-coverage
          fail_ci_if_error: false

  integration-test:
    name: 集成测试
    runs-on: ubuntu-latest
    needs: test-login-register

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 使用 Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: 安装依赖
        run: npm ci

      - name: 启动应用并运行集成测试
        run: |
          # 启动应用
          npm run dev &
          # 等待应用启动
          sleep 10
          # 运行集成测试
          npm run test -- --testPathPattern="integration" --runInBand
        env:
          NODE_ENV: unittest
